package org.apache.roller.ui.authoring.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="bookmarkForm"
 */
public class BookmarkForm
    extends    org.apache.struts.validator.ValidatorForm
    implements java.io.Serializable
{
    protected java.lang.String id;
    protected java.lang.String name;
    protected java.lang.String description;
    protected java.lang.String url;
    protected java.lang.Integer weight;
    protected java.lang.Integer priority;
    protected java.lang.String image;
    protected java.lang.String feedUrl;
    protected org.apache.roller.pojos.FolderData folder;
    protected org.apache.roller.pojos.WebsiteData website;

    /** Default empty constructor. */
    public BookmarkForm() {}

    /** Constructor that takes the data object as argument. */
    public BookmarkForm(org.apache.roller.pojos.BookmarkData dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public java.lang.String getName()
    {
        return this.name;
    }

   /** 
    * @struts.validator type="required" msgkey="errors.required"
    * @struts.validator-args arg0resource="bookmarkForm.name"
    */
    public void setName( java.lang.String name )
    {
        this.name = name;
    }

    public java.lang.String getDescription()
    {
        return this.description;
    }

   /** 
    */
    public void setDescription( java.lang.String description )
    {
        this.description = description;
    }

    public java.lang.String getUrl()
    {
        return this.url;
    }

   /** 
    */
    public void setUrl( java.lang.String url )
    {
        this.url = url;
    }

    public java.lang.Integer getWeight()
    {
        return this.weight;
    }

   /** 
    * @struts.validator type="required" msgkey="errors.required"
    * @struts.validator type="integer" msgkey="errors.integer"
    * @struts.validator-args arg0resource="bookmarkForm.weight"
    */
    public void setWeight( java.lang.Integer weight )
    {
        this.weight = weight;
    }

    public java.lang.Integer getPriority()
    {
        return this.priority;
    }

   /** 
    * @struts.validator type="required" msgkey="errors.required"
    * @struts.validator type="integer" msgkey="errors.integer"
    * @struts.validator-args arg0resource="bookmarkForm.priority"
    */
    public void setPriority( java.lang.Integer priority )
    {
        this.priority = priority;
    }

    public java.lang.String getImage()
    {
        return this.image;
    }

   /** 
    */
    public void setImage( java.lang.String image )
    {
        this.image = image;
    }

    public java.lang.String getFeedUrl()
    {
        return this.feedUrl;
    }

   /** 
    */
    public void setFeedUrl( java.lang.String feedUrl )
    {
        this.feedUrl = feedUrl;
    }

    public org.apache.roller.pojos.FolderData getFolder()
    {
        return this.folder;
    }

   /** 
    */
    public void setFolder( org.apache.roller.pojos.FolderData folder )
    {
        this.folder = folder;
    }

    public org.apache.roller.pojos.WebsiteData getWebsite()
    {
        return this.website;
    }

   /** 
    */
    public void setWebsite( org.apache.roller.pojos.WebsiteData website )
    {
        this.website = website;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.pojos.BookmarkData dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setId(this.id);

        dataHolder.setName(this.name);

        dataHolder.setDescription(this.description);

        dataHolder.setUrl(this.url);

        dataHolder.setWeight(this.weight);

        dataHolder.setPriority(this.priority);

        dataHolder.setImage(this.image);

        dataHolder.setFeedUrl(this.feedUrl);

    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.pojos.BookmarkData dataHolder, Locale locale) throws RollerException
    {

        this.id = dataHolder.getId();

        this.name = dataHolder.getName();

        this.description = dataHolder.getDescription();

        this.url = dataHolder.getUrl();

        this.weight = dataHolder.getWeight();

        this.priority = dataHolder.getPriority();

        this.image = dataHolder.getImage();

        this.feedUrl = dataHolder.getFeedUrl();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.id = null;

        this.name = null;

        this.description = null;

        this.url = null;

        this.weight = null;

        this.priority = null;

        this.image = null;

        this.feedUrl = null;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
