package org.apache.roller.ui.authoring.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="folderForm"
 */
public class FolderForm
    extends    org.apache.struts.validator.ValidatorForm
    implements java.io.Serializable
{
    protected java.lang.Class assocClass;
    protected java.lang.String objectPropertyName;
    protected java.lang.String ancestorPropertyName;
    protected boolean inUse;
    protected java.lang.String id;
    protected java.lang.String name;
    protected java.lang.String description;
    protected java.lang.String path;
    protected org.apache.roller.pojos.WebsiteData website;
    protected org.apache.roller.pojos.FolderData parent;
    protected java.util.List folders;
    protected java.util.Set bookmarks;
    protected org.apache.roller.pojos.Assoc parentAssoc;
    protected java.util.List childAssocs;
    protected java.util.List allDescendentAssocs;
    protected java.util.List ancestorAssocs;
    protected org.apache.roller.pojos.HierarchicalPersistentObject newParent;

    /** Default empty constructor. */
    public FolderForm() {}

    /** Constructor that takes the data object as argument. */
    public FolderForm(org.apache.roller.pojos.FolderData dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public java.lang.Class getAssocClass()
    {
        return this.assocClass;
    }

   /** 
    */
    public void setAssocClass( java.lang.Class assocClass )
    {
        this.assocClass = assocClass;
    }

    public java.lang.String getObjectPropertyName()
    {
        return this.objectPropertyName;
    }

   /** 
    */
    public void setObjectPropertyName( java.lang.String objectPropertyName )
    {
        this.objectPropertyName = objectPropertyName;
    }

    public java.lang.String getAncestorPropertyName()
    {
        return this.ancestorPropertyName;
    }

   /** 
    */
    public void setAncestorPropertyName( java.lang.String ancestorPropertyName )
    {
        this.ancestorPropertyName = ancestorPropertyName;
    }

    public boolean isInUse()
    {
        return this.inUse;
    }

   /** 
    */
    public void setInUse( boolean inUse )
    {
        this.inUse = inUse;
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public java.lang.String getName()
    {
        return this.name;
    }

   /** 
    * @struts.validator type="required" msgkey="errors.required"
    * @struts.validator type="mask" msgkey="errors.noslashes"
    * @struts.validator-args arg0resource="folderForm.name"
    * @struts.validator-var name="mask" value="${noslashes}"
    */
    public void setName( java.lang.String name )
    {
        this.name = name;
    }

    public java.lang.String getDescription()
    {
        return this.description;
    }

   /** 
    */
    public void setDescription( java.lang.String description )
    {
        this.description = description;
    }

    public java.lang.String getPath()throws org.apache.roller.RollerException
    {
        return this.path;
    }

   /** 
    */
    public void setPath( java.lang.String path )
    {
        this.path = path;
    }

    public org.apache.roller.pojos.WebsiteData getWebsite()
    {
        return this.website;
    }

   /** 
    */
    public void setWebsite( org.apache.roller.pojos.WebsiteData website )
    {
        this.website = website;
    }

    public org.apache.roller.pojos.FolderData getParent()throws org.apache.roller.RollerException
    {
        return this.parent;
    }

   /** 
    */
    public void setParent( org.apache.roller.pojos.FolderData parent )
    {
        this.parent = parent;
    }

    public java.util.List getFolders()throws org.apache.roller.RollerException
    {
        return this.folders;
    }

   /** 
    */
    public void setFolders( java.util.List folders )
    {
        this.folders = folders;
    }

    public java.util.Set getBookmarks()
    {
        return this.bookmarks;
    }

   /** 
    */
    public void setBookmarks( java.util.Set bookmarks )
    {
        this.bookmarks = bookmarks;
    }

    public org.apache.roller.pojos.Assoc getParentAssoc()throws org.apache.roller.RollerException
    {
        return this.parentAssoc;
    }

   /** 
    */
    public void setParentAssoc( org.apache.roller.pojos.Assoc parentAssoc )
    {
        this.parentAssoc = parentAssoc;
    }

    public java.util.List getChildAssocs()throws org.apache.roller.RollerException
    {
        return this.childAssocs;
    }

   /** 
    */
    public void setChildAssocs( java.util.List childAssocs )
    {
        this.childAssocs = childAssocs;
    }

    public java.util.List getAllDescendentAssocs()throws org.apache.roller.RollerException
    {
        return this.allDescendentAssocs;
    }

   /** 
    */
    public void setAllDescendentAssocs( java.util.List allDescendentAssocs )
    {
        this.allDescendentAssocs = allDescendentAssocs;
    }

    public java.util.List getAncestorAssocs()throws org.apache.roller.RollerException
    {
        return this.ancestorAssocs;
    }

   /** 
    */
    public void setAncestorAssocs( java.util.List ancestorAssocs )
    {
        this.ancestorAssocs = ancestorAssocs;
    }

    public org.apache.roller.pojos.HierarchicalPersistentObject getNewParent()
    {
        return this.newParent;
    }

   /** 
    */
    public void setNewParent( org.apache.roller.pojos.HierarchicalPersistentObject newParent )
    {
        this.newParent = newParent;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.pojos.FolderData dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setObjectPropertyName(this.objectPropertyName);

        dataHolder.setAncestorPropertyName(this.ancestorPropertyName);

        dataHolder.setInUse(this.inUse);

        dataHolder.setId(this.id);

        dataHolder.setName(this.name);

        dataHolder.setDescription(this.description);

        dataHolder.setPath(this.path);

    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.pojos.FolderData dataHolder, Locale locale) throws RollerException
    {

        this.objectPropertyName = dataHolder.getObjectPropertyName();

        this.ancestorPropertyName = dataHolder.getAncestorPropertyName();

        this.inUse = dataHolder.isInUse();

        this.id = dataHolder.getId();

        this.name = dataHolder.getName();

        this.description = dataHolder.getDescription();

        this.path = dataHolder.getPath();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.objectPropertyName = null;

        this.ancestorPropertyName = null;

        this.inUse = false;

        this.id = null;

        this.name = null;

        this.description = null;

        this.path = null;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
