package org.apache.roller.ui.authoring.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="pingTargetForm"
 */
public class PingTargetForm
    extends    org.apache.struts.action.ActionForm
    implements java.io.Serializable
{
    protected java.lang.String id;
    protected java.lang.String name;
    protected java.lang.String pingUrl;
    protected org.apache.roller.pojos.WebsiteData website;
    protected int conditionCode;
    protected java.sql.Timestamp lastSuccess;
    protected boolean autoEnabled;

    /** Default empty constructor. */
    public PingTargetForm() {}

    /** Constructor that takes the data object as argument. */
    public PingTargetForm(org.apache.roller.pojos.PingTargetData dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    * @struts.validator type="required" msgkey="errors.required"
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public java.lang.String getName()
    {
        return this.name;
    }

   /** 
    */
    public void setName( java.lang.String name )
    {
        this.name = name;
    }

    public java.lang.String getPingUrl()
    {
        return this.pingUrl;
    }

   /** 
    */
    public void setPingUrl( java.lang.String pingUrl )
    {
        this.pingUrl = pingUrl;
    }

    public org.apache.roller.pojos.WebsiteData getWebsite()
    {
        return this.website;
    }

   /** 
    */
    public void setWebsite( org.apache.roller.pojos.WebsiteData website )
    {
        this.website = website;
    }

    public int getConditionCode()
    {
        return this.conditionCode;
    }

   /** 
    */
    public void setConditionCode( int conditionCode )
    {
        this.conditionCode = conditionCode;
    }

    public java.sql.Timestamp getLastSuccess()
    {
        return this.lastSuccess;
    }

   /** 
    */
    public void setLastSuccess( java.sql.Timestamp lastSuccess )
    {
        this.lastSuccess = lastSuccess;
    }

    public boolean isAutoEnabled()
    {
        return this.autoEnabled;
    }

   /** 
    */
    public void setAutoEnabled( boolean autoEnabled )
    {
        this.autoEnabled = autoEnabled;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.pojos.PingTargetData dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setId(this.id);

        dataHolder.setName(this.name);

        dataHolder.setPingUrl(this.pingUrl);

        dataHolder.setConditionCode(this.conditionCode);

        dataHolder.setLastSuccess(this.lastSuccess);

        dataHolder.setAutoEnabled(this.autoEnabled);

    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.pojos.PingTargetData dataHolder, Locale locale) throws RollerException
    {

        this.id = dataHolder.getId();

        this.name = dataHolder.getName();

        this.pingUrl = dataHolder.getPingUrl();

        this.conditionCode = dataHolder.getConditionCode();

        this.lastSuccess = dataHolder.getLastSuccess();

        this.autoEnabled = dataHolder.isAutoEnabled();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.id = null;

        this.name = null;

        this.pingUrl = null;

        this.conditionCode = 0;

        this.lastSuccess = null;

        this.autoEnabled = false;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
