package org.apache.roller.ui.authoring.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="roleForm"
 */
public class RoleForm
    extends    org.apache.struts.action.ActionForm
    implements java.io.Serializable
{
    protected java.lang.String id;
    protected java.lang.String userName;
    protected org.apache.roller.pojos.UserData user;
    protected java.lang.String role;

    /** Default empty constructor. */
    public RoleForm() {}

    /** Constructor that takes the data object as argument. */
    public RoleForm(org.apache.roller.pojos.RoleData dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public java.lang.String getUserName()
    {
        return this.userName;
    }

   /** 
    */
    public void setUserName( java.lang.String userName )
    {
        this.userName = userName;
    }

    public org.apache.roller.pojos.UserData getUser()
    {
        return this.user;
    }

   /** 
    */
    public void setUser( org.apache.roller.pojos.UserData user )
    {
        this.user = user;
    }

    public java.lang.String getRole()
    {
        return this.role;
    }

   /** 
    */
    public void setRole( java.lang.String role )
    {
        this.role = role;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.pojos.RoleData dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setId(this.id);

        dataHolder.setUserName(this.userName);

        dataHolder.setRole(this.role);

    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.pojos.RoleData dataHolder, Locale locale) throws RollerException
    {

        this.id = dataHolder.getId();

        this.userName = dataHolder.getUserName();

        this.role = dataHolder.getRole();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.id = null;

        this.userName = null;

        this.role = null;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
