package org.apache.roller.ui.authoring.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="weblogTemplateForm"
 */
public class WeblogTemplateForm
    extends    org.apache.struts.action.ActionForm
    implements java.io.Serializable
{
    protected org.apache.roller.pojos.Template decorator;
    protected java.lang.String id;
    protected org.apache.roller.pojos.WebsiteData website;
    protected java.lang.String name;
    protected java.lang.String description;
    protected java.lang.String link;
    protected java.lang.String contents;
    protected java.util.Date lastModified;
    protected java.lang.String templateLanguage;
    protected boolean navbar;
    protected boolean hidden;
    protected java.lang.String decoratorName;
    protected boolean required;

    /** Default empty constructor. */
    public WeblogTemplateForm() {}

    /** Constructor that takes the data object as argument. */
    public WeblogTemplateForm(org.apache.roller.pojos.WeblogTemplate dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public org.apache.roller.pojos.Template getDecorator()
    {
        return this.decorator;
    }

   /** 
    */
    public void setDecorator( org.apache.roller.pojos.Template decorator )
    {
        this.decorator = decorator;
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public org.apache.roller.pojos.WebsiteData getWebsite()
    {
        return this.website;
    }

   /** 
    */
    public void setWebsite( org.apache.roller.pojos.WebsiteData website )
    {
        this.website = website;
    }

    public java.lang.String getName()
    {
        return this.name;
    }

   /** 
    */
    public void setName( java.lang.String name )
    {
        this.name = name;
    }

    public java.lang.String getDescription()
    {
        return this.description;
    }

   /** 
    */
    public void setDescription( java.lang.String description )
    {
        this.description = description;
    }

    public java.lang.String getLink()
    {
        return this.link;
    }

   /** 
    */
    public void setLink( java.lang.String link )
    {
        this.link = link;
    }

    public java.lang.String getContents()
    {
        return this.contents;
    }

   /** 
    */
    public void setContents( java.lang.String contents )
    {
        this.contents = contents;
    }

    public java.util.Date getLastModified()
    {
        return this.lastModified;
    }

   /** 
    */
    public void setLastModified( java.util.Date lastModified )
    {
        this.lastModified = lastModified;
    }

    public java.lang.String getTemplateLanguage()
    {
        return this.templateLanguage;
    }

   /** 
    */
    public void setTemplateLanguage( java.lang.String templateLanguage )
    {
        this.templateLanguage = templateLanguage;
    }

    public boolean isNavbar()
    {
        return this.navbar;
    }

   /** 
    */
    public void setNavbar( boolean navbar )
    {
        this.navbar = navbar;
    }

    public boolean isHidden()
    {
        return this.hidden;
    }

   /** 
    */
    public void setHidden( boolean hidden )
    {
        this.hidden = hidden;
    }

    public java.lang.String getDecoratorName()
    {
        return this.decoratorName;
    }

   /** 
    */
    public void setDecoratorName( java.lang.String decoratorName )
    {
        this.decoratorName = decoratorName;
    }

    public boolean isRequired()
    {
        return this.required;
    }

   /** 
    */
    public void setRequired( boolean required )
    {
        this.required = required;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.pojos.WeblogTemplate dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setId(this.id);

        dataHolder.setName(this.name);

        dataHolder.setDescription(this.description);

        dataHolder.setLink(this.link);

        dataHolder.setContents(this.contents);

        dataHolder.setLastModified(this.lastModified);

        dataHolder.setTemplateLanguage(this.templateLanguage);

        dataHolder.setNavbar(this.navbar);

        dataHolder.setHidden(this.hidden);

        dataHolder.setDecoratorName(this.decoratorName);

        dataHolder.setRequired(this.required);

    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.pojos.WeblogTemplate dataHolder, Locale locale) throws RollerException
    {

        this.id = dataHolder.getId();

        this.name = dataHolder.getName();

        this.description = dataHolder.getDescription();

        this.link = dataHolder.getLink();

        this.contents = dataHolder.getContents();

        this.lastModified = dataHolder.getLastModified();

        this.templateLanguage = dataHolder.getTemplateLanguage();

        this.navbar = dataHolder.isNavbar();

        this.hidden = dataHolder.isHidden();

        this.decoratorName = dataHolder.getDecoratorName();

        this.required = dataHolder.isRequired();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.id = null;

        this.name = null;

        this.description = null;

        this.link = null;

        this.contents = null;

        this.lastModified = null;

        this.templateLanguage = null;

        this.navbar = false;

        this.hidden = false;

        this.decoratorName = null;

        this.required = false;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
