package org.apache.roller.ui.authoring.struts.forms;

import org.apache.roller.RollerException;
import java.util.Locale;

/**
 * Generated by XDoclet/ejbdoclet/strutsform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="websiteDisplayForm"
 */
public class WebsiteDisplayForm
    extends    org.apache.struts.action.ActionForm
    implements java.io.Serializable
{
    protected java.lang.String id;
    protected java.lang.Integer hits;
    protected java.lang.String websiteName;
    protected java.lang.String websiteHandle;

    /** Default empty constructor. */
    public WebsiteDisplayForm() {}

    /** Constructor that takes the data object as argument. */
    public WebsiteDisplayForm(org.apache.roller.pojos.WebsiteDisplayData dataHolder, java.util.Locale locale) throws RollerException
    {
       copyFrom(dataHolder, locale);
    }

    public java.lang.String getId()
    {
        return this.id;
    }

   /** 
    */
    public void setId( java.lang.String id )
    {
        this.id = id;
    }

    public java.lang.Integer getHits()
    {
        return this.hits;
    }

   /** 
    */
    public void setHits( java.lang.Integer hits )
    {
        this.hits = hits;
    }

    public java.lang.String getWebsiteName()
    {
        return this.websiteName;
    }

   /** 
    */
    public void setWebsiteName( java.lang.String websiteName )
    {
        this.websiteName = websiteName;
    }

    public java.lang.String getWebsiteHandle()
    {
        return this.websiteHandle;
    }

   /** 
    */
    public void setWebsiteHandle( java.lang.String websiteHandle )
    {
        this.websiteHandle = websiteHandle;
    }

    /**
     * Copy values from this form bean to the specified data object.
     * Only copies primitive types (Boolean, boolean, String, Integer, int, Timestamp, Date)
     */
    public void copyTo(org.apache.roller.pojos.WebsiteDisplayData dataHolder, Locale locale) throws RollerException
    {

        dataHolder.setId(this.id);

        dataHolder.setHits(this.hits);

        dataHolder.setWebsiteName(this.websiteName);

        dataHolder.setWebsiteHandle(this.websiteHandle);

    }

    /**
     * Copy values from specified data object to this form bean.
     * Includes all types.
     */
    public void copyFrom(org.apache.roller.pojos.WebsiteDisplayData dataHolder, Locale locale) throws RollerException
    {

        this.id = dataHolder.getId();

        this.hits = dataHolder.getHits();

        this.websiteName = dataHolder.getWebsiteName();

        this.websiteHandle = dataHolder.getWebsiteHandle();

    }

    public void doReset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {

        this.id = null;

        this.hits = null;

        this.websiteName = null;

        this.websiteHandle = null;

    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.ServletRequest request)
    {
        doReset(mapping, request);
    }
    public void reset(
    	org.apache.struts.action.ActionMapping mapping, 
    	javax.servlet.http.HttpServletRequest request)
    {
        doReset(mapping, request);
    }
}
