
##
## Shell Functions for CMPE279 Labs
## (Append to ~/.bashrc)
##

function clean() {
  rm *.o *.out
}

function assemble() {
  nasm -f elf -g -F stabs $1.asm
  ld -o $1.out $1.o
}

function compile() {
  gcc -ggdb -m32 $1.c -o $1.out 
}

function unsafe_compile() {
  gcc -fno-stack-protector -ggdb -m32 $1.c -o $1.out
}

function gdb_attach() {
  gdb -tui -p $1
}

function run_hex() {
  while read -r line; do echo -e $line; done | $1
}

